# Generated by Django 5.2.17 on 2026-09-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_place_options_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['title', 'position_number'], 'verbose_name': 'картинка', 'verbose_name_plural': 'картинки'},
        ),
        migrations.AddField(
            model_name='image',
            name='position_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер картинки в расположении'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='places_images/', verbose_name='Картинка'),
        ),
    ]
