# Generated by Django 5.2.17 on 2026-09-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='place_id',
            field=models.CharField(default='msk', max_length=50, verbose_name='Уникальный идентификатор локации'),
            preserve_default=False,
        ),
    ]
