# Generated by Django 5.2.17 on 2026-09-10 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_place_place_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='file',
        ),
    ]
