# Generated by Django 5.2.17 on 2026-09-12 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_rename_image_image_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['position_number'], 'verbose_name': 'картинка', 'verbose_name_plural': 'картинки'},
        ),
        migrations.AlterField(
            model_name='image',
            name='position_number',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Номер картинки в расположении'),
        ),
    ]
