# Generated by Django 5.2.17 on 2026-09-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_alter_place_description_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='Уникальный идентификатор локации'),
        ),
    ]
