# Generated by Django 5.2.17 on 2026-09-15 16:01

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.CharField(max_length=200, unique=True, verbose_name='Уникальный идентификатор локации')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('short_description', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('long_description', tinymce.models.HTMLField(blank=True, verbose_name='Полное описание')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
            ],
            options={
                'verbose_name': 'место',
                'verbose_name_plural': 'места',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='media/', verbose_name='Картинка')),
                ('position_number', models.PositiveSmallIntegerField(default=0, verbose_name='порядковый номер')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='where_to_go.place', verbose_name='локация картинки')),
            ],
            options={
                'verbose_name': 'картинка',
                'verbose_name_plural': 'картинки',
                'ordering': ['position_number'],
                'indexes': [models.Index(fields=['position_number'], name='where_to_go_positio_d7d9f2_idx')],
            },
        ),
    ]
