# Generated by Django 5.2.17 on 2026-09-15 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('where_to_go', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='place_id',
        ),
    ]
